### PR TITLE
JAMES-1975 Extract Mailet code out of JDKIM

### PR DESCRIPTION
**Pull request by chibenwa**

### CODE REVIEW

**Comment by chibenwa** [comment]
Combines with https://github.com/linagora/james-project/pull/722

Rebase of https://github.com/apache/james-jdkim/pull/5

**Review by quynhn — APPROVED** [review]

**Comment by mbaechler** [comment]
What was missing to merge it ?

**Comment by chibenwa** [comment]
One more approuval.

And a CI build.

**Comment by chibenwa** [comment]
Merged in another PR

**Pull request closed without merging**
